name: Publish Unity Package

on: 
  workflow_call:
    
jobs: 
  Publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://duy-npm.com/'
      - run: npm publish
        working-directory: ./Assets
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}